### ISSUE TITLE
Make zsh installation idempotent and add error handling

### ISSUE THREAD

**Issue by niklasdewally** [STAOJ/sta-setup#2]
The zsh installation needs to be made idempotent - when the script is ran multiple times, there should not be any errors due to directories already existing / cloning into a directory with an existing git repo. Also, any changes to the system (such as `.bashrc`) should only occur once and not be applied again when the script is reran.

This would allow proper error handling code to be written, as only actual errors would be present, instead of `cannot mkdir: directory already exists` type of messages.

Using a trap at the start of the file would work, for example:
```bash
set -E # catch errors inside functions and subshells
trap "err_handle" ERR

err_handle () {
# error handling code here
} 
```

As discussed previously here: https://github.com/CP-STA/sta-setup/pull/1#discussion_r911272395.

**Comment by DE0CH** [comment]
Right, also for installing brew, should we add a test at the beginning to detect if brew is installed? Currently even though it is idempotent, it still outputs warnings that gcc is installed.
